#!/usr/bin/env python3
"""
AIOS Command Line Tool

Author : AIOS Project
License: MIT

Currently supported:

    aiosctl.py sync

Future:

    aiosctl.py validate
    aiosctl.py doctor
    aiosctl.py init
    aiosctl.py version
"""

from __future__ import annotations

import argparse
import hashlib
import logging
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import List


# ----------------------------------------------------
# Constants
# ----------------------------------------------------


AIOS_RULE_DIR = "rules"
TARGET_RULE_DIR = ".agents"

VERSION_FILE = "AIOS_VERSION.md"

GENERATED_HEADER = """\
# ======================================================
# THIS FILE IS AUTO-GENERATED
#
# Source:
#   AIOS/rules
#
# DO NOT EDIT THIS FILE MANUALLY.
#
# Changes will be overwritten by aiosctl sync.
# ======================================================

"""


# ----------------------------------------------------
# Logger
# ----------------------------------------------------

logging.basicConfig(
    level=logging.INFO,
    format="%(message)s"
)

log = logging.getLogger("AIOS")


# ----------------------------------------------------
# Dataclasses
# ----------------------------------------------------

@dataclass
class SyncOptions:

    project: Path

    force: bool = False

    dry_run: bool = False


# ----------------------------------------------------
# Helpers
# ----------------------------------------------------

def read_text(path: Path) -> str:

    return path.read_text(
        encoding="utf-8"
    )


def write_text(path: Path, text: str):

    path.write_text(
        text,
        encoding="utf-8"
    )


def ensure_directory(path: Path):

    path.mkdir(
        parents=True,
        exist_ok=True
    )


# ----------------------------------------------------
# AIOS Discovery
# ----------------------------------------------------

def discover_aios_root() -> Path:
    root = Path(__file__).resolve().parent.parent

    if not (root / "rules").exists():
        raise RuntimeError(
            f"AIOS rules directory not found: {root / 'rules'}"
        )

    return root


# ----------------------------------------------------
# Project Validation
# ----------------------------------------------------

def validate_project(project: Path):

    if not project.exists():

        raise FileNotFoundError(project)

    if not project.is_dir():

        raise RuntimeError(
            f"{project} is not a directory."
        )


# ----------------------------------------------------
# Rule Discovery
# ----------------------------------------------------

def discover_rule_files(
    rules_directory: Path
) -> List[Path]:

    return sorted(
        rules_directory.glob("*.md")
    )
# ----------------------------------------------------
# Header
# ----------------------------------------------------

def build_header() -> str:
    """
    Returns the standard generated header.
    """
    return GENERATED_HEADER + "\n"


# ----------------------------------------------------
# Version File
# ----------------------------------------------------

def write_version_file(aios_root: Path, target: Path) -> None:
    """
    Creates AIOS_VERSION.md in the target repository.
    """

    version_text = f"""# AIOS Rule Synchronization

Generated: {datetime.now():%Y-%m-%d %H:%M:%S}

Source:
{aios_root}

Managed by:

    aiosctl sync

Do not edit manually.
"""

    write_text(target / VERSION_FILE, version_text)


# ----------------------------------------------------
# File Copy
# ----------------------------------------------------

def copy_rule(
    source: Path,
    destination: Path,
    force: bool = False,
    dry_run: bool = False,
) -> bool:
    """
    Copies a rule only if necessary.

    Returns
    -------
    True  -> copied
    False -> skipped
    """

    source_content = build_header() + read_text(source)

    if destination.exists() and not force:

        destination_content = read_text(destination)

        if hashlib.sha256(source_content.encode()).hexdigest() == \
           hashlib.sha256(destination_content.encode()).hexdigest():

            log.info(f"SKIP   {destination.name}")

            return False

    if dry_run:

        log.info(f"DRY    {destination.name}")

        return True

    write_text(destination, source_content)

    log.info(f"COPY   {destination.name}")

    return True


# ----------------------------------------------------
# Sync Project
# ----------------------------------------------------

def sync_project(
    aios_root: Path,
    options: SyncOptions,
):
    """
    Synchronize one project.
    """

    validate_project(options.project)

    rules_dir = aios_root / AIOS_RULE_DIR

    target_dir = options.project / TARGET_RULE_DIR

    ensure_directory(target_dir)

    rule_files = discover_rule_files(rules_dir)

    copied = 0
    skipped = 0

    log.info("")
    log.info("=" * 60)
    log.info(f"Project : {options.project.name}")
    log.info("=" * 60)

    for rule in rule_files:

        result = copy_rule(
            source=rule,
            destination=target_dir / rule.name,
            force=options.force,
            dry_run=options.dry_run,
        )

        if result:
            copied += 1
        else:
            skipped += 1

    if not options.dry_run:
        write_version_file(
            aios_root,
            target_dir,
        )

    log.info("")
    log.info(f"Copied : {copied}")
    log.info(f"Skipped: {skipped}")
    log.info("")
    # ----------------------------------------------------
# CLI
# ----------------------------------------------------

def create_parser() -> argparse.ArgumentParser:
    """
    Create the command line parser.
    """

    parser = argparse.ArgumentParser(
        prog="aiosctl",
        description="AIOS Command Line Tool"
    )

    subparsers = parser.add_subparsers(
        dest="command",
        required=True,
    )

    # --------------------------------------------
    # sync
    # --------------------------------------------

    sync = subparsers.add_parser(
        "sync",
        help="Synchronize AIOS rule files."
    )

    sync.add_argument(
        "--project",
        required=True,
        type=Path,
        help="Target project directory"
    )

    sync.add_argument(
        "--force",
        action="store_true",
        help="Overwrite existing files."
    )

    sync.add_argument(
        "--dry-run",
        action="store_true",
        help="Show changes without writing files."
    )

    return parser


# ----------------------------------------------------
# Commands
# ----------------------------------------------------

def command_sync(args):

    aios_root = discover_aios_root()

    options = SyncOptions(
        project=args.project,
        force=args.force,
        dry_run=args.dry_run,
    )

    log.info("")
    log.info("============================================")
    log.info(" AIOS Rule Synchronization")
    log.info("============================================")
    log.info("")

    log.info(f"AIOS Root : {aios_root}")
    log.info(f"Project   : {options.project}")
    log.info("")

    sync_project(
        aios_root,
        options,
    )

    log.info("")
    log.info("Synchronization completed.")
    log.info("")


# ----------------------------------------------------
# Main
# ----------------------------------------------------

def main():

    parser = create_parser()

    args = parser.parse_args()

    try:

        if args.command == "sync":

            command_sync(args)

        else:

            parser.print_help()

    except KeyboardInterrupt:

        log.error("\nInterrupted.")

    except Exception as ex:

        log.error("")
        log.error("=" * 60)
        log.error("ERROR")
        log.error("=" * 60)
        log.error(str(ex))
        log.error("")


# ----------------------------------------------------
# Entry
# ----------------------------------------------------

if __name__ == "__main__":
    main()